variable "public_key_path" {
  default = "terraform/deploy/public.pem"
}

resource "aws_cloudfront_public_key" "cf_public_key" {
  name       = "cf_public_key"
  encoded_key = file(var.public_key_path)
  comment    = "CloudFront public key generated by GitHub Actions"
}

resource "aws_cloudfront_key_group" "cf_key_group" {
  name = "cf_key_group"
  items = [
    aws_cloudfront_public_key.cf_public_key.id
  ]
}

resource "aws_cloudfront_distribution" "cf_distribution" {
  # ... existing CloudFront configurations ...

  default_cache_behavior {
    # ... other settings...
    trusted_key_groups = [aws_cloudfront_key_group.cf_key_group.id]
  }
}

output "cloudfront_distribution_id" {
  value = aws_cloudfront_distribution.my_distribution.id
}