name: CloudFront Key Management

on:
  workflow_dispatch:

jobs:
  manage-cloudfront-key:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Generate timestamp for resource names
        id: ts
        run: |
          echo "TS=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Generate RSA key pair
        run: |
          openssl genrsa -out private.pem 2048
          openssl rsa -pubout -in private.pem -out public.pem

      - name: Upload private key to AWS Secrets Manager
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          SECRET_NAME: cloudfront-private-key-${{ env.TS }}
        run: |
          if aws secretsmanager describe-secret --secret-id "$SECRET_NAME" --region "$AWS_REGION" > /dev/null 2>&1; then
            aws secretsmanager put-secret-value --secret-id "$SECRET_NAME" --secret-string file://private.pem --region "$AWS_REGION"
          else
            aws secretsmanager create-secret --name "$SECRET_NAME" --secret-string file://private.pem --region "$AWS_REGION"
          fi

      - name: Prepare Terraform public key file
        run: |
          cp public.pem terraform/cloudfront-key/public.pem

      - name: Terraform Init
        working-directory: terraform/cloudfront-key
        run: terraform init -input=false -upgrade

      - name: Terraform Apply
        working-directory: terraform/cloudfront-key
        env:
          CF_PUBLIC_KEY_NAME: cf-public-key-${{ env.TS }}
          CF_KEY_GROUP_NAME: cf-key-group-${{ env.TS }}
        run: |
          terraform apply -auto-approve \
            -var="cf_public_key_name=$CF_PUBLIC_KEY_NAME" \
            -var="cf_key_group_name=$CF_KEY_GROUP_NAME"

      - name: Get CloudFront Key Group ID output from Terraform
        id: keygroup_output
        working-directory: terraform/cloudfront-key
        run: |
          id=$(terraform output -raw cloudfront_key_group_id)
          echo "$id" > ../../CLOUDFRONT_KEY_GROUP_ID.txt
          echo "${{ env.SECRET_NAME }}" > ../../CLOUDFRONT_PRIVATE_KEY_SECRET_NAME.txt

      - name: Upload Key Group ID artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudfront-key-group-id
          path: CLOUDFRONT_KEY_GROUP_ID.txt

      - name: Upload Private Key Secret Name artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudfront-private-key-secret-name
          path: CLOUDFRONT_PRIVATE_KEY_SECRET_NAME.txt
