name: Build and Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      BUCKET_NAME: aws-pet-bucket
      TF_VAR_alpha_vantage_apikey: ${{ secrets.ALPHA_VANTAGE_APIKEY }}
      TF_LOG: DEBUG

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build project with Maven
        run: mvn clean package
        
        # checking the current terraform scripts before trying to apply it
        
      - name: Terraform Init
        working-directory: terraform/deploy
        run: terraform init -input=false -upgrade

      - name: Terraform Plan
        working-directory: terraform/deploy
        run: terraform plan

      - name: Import existing resources if not in state then apply
        working-directory: terraform/deploy
        run: |
          echo "Importing existing resources (ignoring errors)..."
          terraform import aws_s3_bucket.lambda_bucket $BUCKET_NAME || true
          terraform import aws_iam_role.lambda_exec_role lambda_execution_role || true
          echo "Starting terraform apply..."
          terraform apply -auto-approve
          echo "Terraform apply completed."
