name: Build and Deploy to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      BUCKET_NAME: aws-pet-bucket
      ARTIFACTS_BUCKET_NAME: aws-pet-project-build-artifacts 
      TF_VAR_alpha_vantage_apikey: ${{ secrets.ALPHA_VANTAGE_APIKEY }}
      TF_LOG: DEBUG

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build project with Maven
        run: mvn clean package

      - name: S3 artifact bucket existence test
        run: |
          if aws s3api head-bucket --bucket "$ARTIFACTS_BUCKET_NAME" --region "$AWS_REGION" 2>/dev/null; then
            echo "Bucket $ARTIFACTS_BUCKET_NAME exists, doing nothing."
          else
            echo "Bucket $ARTIFACTS_BUCKET_NAME does not exist -> worfklow will fail"
            exit 1
          fi        

      - name: Download Key Group ID from S3
        run: aws s3 cp s3://$ARTIFACTS_BUCKET_NAME/CLOUDFRONT_KEY_GROUP_ID.txt CLOUDFRONT_KEY_GROUP_ID.txt --region $AWS_REGION

      - name: Download Private Key Secret Name from S3
        run: aws s3 cp s3://$ARTIFACTS_BUCKET_NAME/CLOUDFRONT_PRIVATE_KEY_SECRET_NAME.txt CLOUDFRONT_PRIVATE_KEY_SECRET_NAME.txt --region $AWS_REGION

      - name: Set CLOUDFRONT_KEY_GROUP_ID and PRIVATE_KEY_SECRET_NAME env vars
        run: |
          echo "CLOUDFRONT_KEY_GROUP_ID=$(cat CLOUDFRONT_KEY_GROUP_ID.txt)" >> $GITHUB_ENV
          echo "PRIVATE_KEY_SECRET_NAME=$(cat CLOUDFRONT_PRIVATE_KEY_SECRET_NAME.txt)" >> $GITHUB_ENV      

      - name: Download private key from AWS Secrets Manager
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          aws secretsmanager get-secret-value --secret-id "$PRIVATE_KEY_SECRET_NAME" --region "$AWS_REGION" --query SecretString --output text > private.pem

      - name: Terraform Init
        working-directory: terraform/deploy
        run: terraform init -input=false -upgrade

      - name: Terraform Format Check
        working-directory: terraform/deploy
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: terraform/deploy
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/deploy
        run: terraform plan -var="bucket_name=$BUCKET_NAME" -var="cloudfront_key_group_id=$CLOUDFRONT_KEY_GROUP_ID"

      - name: Terraform Apply
        working-directory: terraform/deploy
        run: terraform apply -auto-approve -var="bucket_name=$BUCKET_NAME" -var="cloudfront_key_group_id=$CLOUDFRONT_KEY_GROUP_ID"

      # log CloudFront Distribution ID to be able to create a github secret out of it for the destroyall github workflow
      - name: Get CloudFront Distribution ID output from Terraform
        id: cloudfront_output
        working-directory: terraform/deploy
        run: |
          dist_id=$(terraform output -raw cloudfront_distribution_id)
          echo "cloudfront_distribution_id=$dist_id" >> "$GITHUB_OUTPUT"

      - name: Log CloudFront Distribution ID
        run: |
          echo "CloudFront Distribution ID: $CLOUDFRONT_DIST_ID"
        env:
          CLOUDFRONT_DIST_ID: ${{ steps.cloudfront_output.outputs.cloudfront_distribution_id }}

